/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.MechanicSystem.view;

import ec.edu.espe.MechanicSystem.model.Auto;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import static java.lang.System.exit;
import static javax.management.Query.lt;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Inforlan
 */
public class frmRegisterNewCar extends javax.swing.JFrame {
    private String ruta_txt = "autos.txt";
    Auto auto;
    Proceso proceso;
    
    

   
    /**
     * Creates new form frmRegisterNewCar
     */
    public frmRegisterNewCar() {
        initComponents();
        setLocation(275,175);
        
    }
    public String leerMarca(){
        try{
            String marca = txtMarca.getText().trim().replace(" ", "_");
            return marca;
        }catch(Exception ex){
            return null;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegisterNewCar = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblDueñoCliente = new javax.swing.JLabel();
        btnCloseRegister = new javax.swing.JButton();
        txtModelo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtDueñoCliente = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        btnRegistarCar = new javax.swing.JButton();
        lblReparacion = new javax.swing.JLabel();
        txtInformacionAuto = new javax.swing.JTextField();
        lblDescripcion1 = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblFonfoNewCarRegister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegisterNewCar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblRegisterNewCar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterNewCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegisterNewCar.setText("REGISTER A NEW CAR");
        getContentPane().add(lblRegisterNewCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 210, 30));

        lblMarca.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarca.setText("MARCA:");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 30));

        lblModelo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(255, 255, 255));
        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModelo.setText("MODELO:");
        getContentPane().add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 30));

        lblColor.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColor.setText("COLOR:");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 30));

        lblPlaca.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca.setText("PLACA:");
        getContentPane().add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 80, 30));

        lblDueñoCliente.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblDueñoCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblDueñoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDueñoCliente.setText("DUEÑO/CLIENTE:");
        getContentPane().add(lblDueñoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 160, 30));

        btnCloseRegister.setText("CLOSE");
        btnCloseRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnCloseRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, 30));
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, 30));
        getContentPane().add(txtDueñoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 160, 30));
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 50, 30));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 100, 30));

        btnRegistarCar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnRegistarCar.setText("REGISTRAR");
        btnRegistarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarCarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistarCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, 30));

        lblReparacion.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblReparacion.setForeground(new java.awt.Color(255, 255, 255));
        lblReparacion.setText("REPARACION/SERVICIO:");
        getContentPane().add(lblReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 190, -1));

        txtInformacionAuto.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        getContentPane().add(txtInformacionAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 290, 80));

        lblDescripcion1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDescripcion1.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion1.setText("Descripcion despues de revision:");
        getContentPane().add(lblDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 190, -1));

        txtServicio.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        getContentPane().add(txtServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 170, 80));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 50, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("-");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 10, -1));

        lblFonfoNewCarRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carfondoRegisterVehicule.jpg"))); // NOI18N
        getContentPane().add(lblFonfoNewCarRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarCarActionPerformed
        File ruta = new File(txtMarca.getText());
       // this.ingresarRegistro(ruta);
    }//GEN-LAST:event_btnRegistarCarActionPerformed

    private void btnCloseRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseRegisterActionPerformed
          this.setVisible(false); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegisterNewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegisterNewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegisterNewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegisterNewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegisterNewCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseRegister;
    private javax.swing.JButton btnRegistarCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDueñoCliente;
    private javax.swing.JLabel lblFonfoNewCarRegister;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblRegisterNewCar;
    private javax.swing.JLabel lblReparacion;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDueñoCliente;
    private javax.swing.JTextField txtInformacionAuto;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables

    /*private void ingresarRegistro(File ruta) {
         try{
            if(leerMarca() == null)
            else if JOptionPane.showMassageDialog(null,"Ingresar la maraca del auto");
            else if(leerModelo() == null)mensaje("Ingresar modelo");
            else if(leerColor() == null) mensaje("Ingresar color");
            else if(leerOwner() == null)mensaje("Ingresar Dueño");
            else{
                p = new Auto(leerMarca(), leerModelo(), leerColor(), leerOwner());
                //if(rp.buscaCodigo(p.getCodigo())!= -1)mensaje("Este codigo ya existe");
                //else rp.agregarRegistro(p);
                
                grabar_txt();
                //listarRegistro();
                lt.limpiar_texto(panel); 
            }
        }catch(Exception ex){
            mensaje(ex.getMessage());
        }
    }
*/
    //void setVisible(boolean b) {
       ; //To change body of generated methods, choose Tools | Templates.
    }


